name: Java CI/CD Pipeline to Tomcat

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Ensure Maven is installed
        run: |
          if ! command -v mvn >/dev/null 2>&1; then
            sudo dnf install -y maven
          fi
          mvn -version

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: target/*.war

      - name: SonarQube Analysis
        env:
          SONAR_HOST: ${{ secrets.SONAR_HOST }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=hotstar \
            -Dsonar.host.url=${SONAR_HOST} \
            -Dsonar.login=${SONAR_TOKEN}

  deploy:
    needs: build
    runs-on: self-hosted
    environment: production

    steps:
      - name: Download WAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp

      - name: Deploy to Tomcat
        run: |
          WAR_FILE=$(ls *.war | head -1)

          curl --upload-file "$WAR_FILE" \
          "http://${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}@${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/myapp&update=true"

      - name: Verify Deployment
        run: |
          curl -I "http://${{ secrets.TOMCAT_HOST }}/myapp"
